allow using volumes with inline_scan
Signed-off-by: Brady Todhunter <bradyt@anchore.com>

diff --git a/scripts/inline_scan b/scripts/inline_scan
--- a/scripts/inline_scan
+++ b/scripts/inline_scan
@@ -18,23 +18,27 @@ Stateless Anchore Engine --
   Images should be built & tagged locally, or remote images can be pulled with the -r option.
 
   
-  Usage: ${0##*/} [ -f ] [ -p ] [ -r ] [ -d ./Dockerfile ] [ -b ./policy.json ] [ IMAGE_ONE ] [ IMAGE_TWO ... ]
+  Usage: ${0##*/} [ -f ] [ -p ] [ -r ] [ -v ./anchore_images ] [ -d ./Dockerfile ] [ -b ./policy.json ] [ IMAGE_ONE ] [ IMAGE_TWO ... ]
 
-      -b  (optional) Path to local Anchore policy bundle
-      -d  (optional) Path to local Dockerfile
-      -f  (optional) Exit script upon failed Anchore policy evaluation
-      -p  (optional) Pull remote docker images
+      -b  [optional] Path to local Anchore policy bundle
+      -d  [optional] Path to local Dockerfile
+      -v  [optional] Path to directory to be mounted as docker volume. All image archives in directory will be scanned.
+      -f  [optional] Exit script upon failed Anchore policy evaluation
+      -p  [optional] Pull remote docker images
       -r  [optional] Generate analysis reports in your current working directory.
  
 EOF
 }
 
 interupt() {
-    cleanup
+    cleanup 130
 }
 
 cleanup() {
     ret="$?"
+    if [[ "${#@}" -ge 1 ]]; then
+        ret="$1"
+    fi
     set +e
 
     if [[ -z "$docker_id" ]]; then
@@ -72,7 +76,7 @@ trap 'cleanup' EXIT ERR SIGTERM
 trap 'interupt' SIGINT
 
 # Parse options
-while getopts ':d:b:fhrp' option; do
+while getopts ':d:b:v:fhrp' option; do
   case "$option" in
     h  ) display_usage; exit;;
     d  ) d_flag=true; dockerfile="$OPTARG";;
@@ -80,6 +84,7 @@ while getopts ':d:b:fhrp' option; do
     r  ) r_flag=true;;
     b  ) b_flag=true; policy_bundle="$OPTARG";;
     p  ) p_flag=true;;
+    v  ) v_flag=true; volume_path="$(cd "$(dirname "$OPTARG")"; pwd -P)/$(basename "$OPTARG")";;
     \? ) printf "\n\t%s\n\n" "  Invalid option: -${OPTARG}" >&2; display_usage >&2; exit 1;;
     :  ) printf "\n\t%s\n\n%s\n\n" "  Option -${OPTARG} requires an argument." >&2; display_usage >&2; exit 1;;
   esac
@@ -107,9 +112,15 @@ elif [[ "$d_flag" ]] && [[ ! -f "$dockerfile" ]]; then
     printf '\n\t%s\n\n' "ERROR - Dockerfile: $dockerfile does not exist." >&2
     display_usage >&2
     exit 1
-elif [[ "${#@}" -eq 0 ]]; then
-    printf '\n\t%s\n\n' "ERROR - ${0##*/} requires at least 1 image name as input." >&2
+elif [[ ! "v_flag" ]] && [[ "${#@}" -eq 0 ]]; then
+    printf '\n\t%s\n\n' "ERROR - ${0##*/} requires at least 1 image name as input, unless utilizing -v option." >&2
     display_usage >&2
+    exit 1
+elif [[ "$v_flag" ]] && [[ ! -d "$volume_path" ]]; then
+    printf '\n\t%s\n\n' "ERROR - $volume_path is not a directory." >&2
+    exit 1
+elif [[ "$v_flag" ]] && [[ "$d_flag" ]]; then
+    printf '\n\t%s\n\n' "ERROR - cannot specify image volume & Dockerfile. Dockerfile option only supports scanning one image at time." >&2
     exit 1
 fi
 
@@ -165,8 +176,13 @@ fi
 docker_name="${RANDOM:-TEMP}-inline-anchore-engine"
 
 copy_cmds=()
-create_cmd=('docker create --name "$docker_name" "$stateless_anchore_image"')
-run_cmd=("docker run -i --name $docker_name $stateless_anchore_image -i${scan_images[*]}")
+run_cmd=("docker run -i --name $docker_name $stateless_anchore_image")
+
+if [[ "$v_flag" ]]; then
+    create_cmd=('docker create -v "${volume_path}:/anchore-engine:rw" --name "$docker_name" "$stateless_anchore_image"')
+else
+    create_cmd=('docker create --name "$docker_name" "$stateless_anchore_image"')
+fi
 
 if [[ "$f_flag" ]]; then
     create_cmd+=('-f')
@@ -178,8 +194,9 @@ if [[ "$r_flag" ]]; then
     run_cmd+=('-r')
 fi
 
-if [[ ! "$d_flag" ]] && [[ ! "$b_flag" ]] && [[ "${#scan_images[@]}" -eq 1 ]]; then
+if [[ ! "$d_flag" ]] && [[ ! "$v_flag" ]] && [[ ! "$b_flag" ]] && [[ "${#scan_images[@]}" -eq 1 ]]; then
     printf '\n%s\n' "Preparing image for analysis -- ${scan_images[*]}"
+    run_cmd+=('-i${scan_images[*]}')
     docker save "$i" | eval "${run_cmd[*]}"
 else
     if [[ "$b_flag" ]]; then
@@ -201,16 +218,24 @@ else
         tag="${image#*:}"
         file_name="${repo}+${tag}.tar" 
         image_files+=("$file_name")
-
-        docker save "$image" -o "/tmp/${file_name}"
-
-        if [[ -f "/tmp/${file_name}" ]]; then
-            docker cp "/tmp/${file_name}" "${docker_name}:/anchore-engine/${file_name}"
-            rm -f "/tmp/${file_name}"
+        
+        if [[ "$v_flag" ]]; then
+            output_file="${volume_path}/${file_name}"
         else
-            printf '\n\t%s\n\n' "ERROR - unable to save docker image to /tmp/${file_name}." >&2
+            output_file="/tmp/${file_name}"
+        fi
+
+        docker save "$image" -o "$output_file"
+
+        if [[ ! -f "$output_file" ]]; then
+            printf '\n\t%s\n\n' "ERROR - unable to save docker image to $output_file." >&2
             display_usage >&2
             exit 1
+        fi
+
+        if [[ ! "$v_flag" ]]; then
+            docker cp "$output_file" "${docker_name}:/anchore-engine/${file_name}"
+            rm -f "$output_file"
         fi
     done
 
